name: Build and push docker image to docker hub
on: 
  push:
    branches:
      - main

env: 
  IMAGE_NAME: latest
  DOCKERHUB_REPOSITORY: mlrene/boxer
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: login to dockerhub 
        uses: docker/login-action@v1
        with: 
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: build the docker image
        run: docker build -t $IMAGE_NAME .
      - name: tag the docker image
        run: docker tag $IMAGE_NAME $DOCKERHUB_REPOSITORY:$IMAGE_NAME
      - name: push to dockerhub
        run: docker push $DOCKERHUB_REPOSITORY:$IMAGE_NAME